### ISSUE TITLE
Opens in the middle of the screen

### ISSUE THREAD

**Issue by AndreGFilho** [Ranork/Pomotro#2]
Hey, loved the design of your pomodoro.
Only problem is that when i start it, it is fixed in the middle of the screen.

Running it on windows 10 with a ultra wide screen in case it helps.

**Comment by Ranork** [comment]
oh thats my first issue i will love to help :D
https://github.com/Ranork/Pomotro/blob/4267c1588d753e5644ed55d73ed39dbb40549efa/main.js#L13
in this line you can see the start positions in x and y.
I tried a 1920x1080 screen.
X is 1920 - 300 (for start menu) = 1620
Y is 1080 - 87 (i cant remember why 87) = 993
